#!/bin/bash

npm install aws-cdk-lib
. ~/.bash_profile
cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
npm install
cdk deploy --app "npx ts-node --prefer-ts-exts ./pipeline.ts" --parameters BASEREPO=$BASE_REPO --parameters BASEIMAGETAG=$BASE_IMAGE_TAG --parameters CODECOMMITREPO=$CODE_COMMIT_REPO


#--parameters CODE_COMMIT_REPO=$CODE_COMMIT_REPO AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID AWS_REGION=$AWS_REGION BASE_REPO=$BASE_REPO BASE_IMAGE_TAG=$BASE_IMAGE_TAG GAME_REPO=$GAME_REPO GAME_ASSETS_TAG=$GAME_ASSETS_TAG GAME_CODE_TAG=$GAME_CODE_TAG GAME_SERVER_TAG=$GAME_SERVER_TAG
