---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: reinvent2022
  region: us-west-2

gitops:
  flux:
    gitProvider: github             # required. options are github or gitlab
    flags:                          # required. arbitrary map[string]string for all flux args.
      owner: "yahavb"
      repository: "gam302r"
      branch: "main"
      namespace: "default"
      path: "./clusters/reinvent2022"
