kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-editor-admin-bind
  namespace: yahavb
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: yahavb
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
