apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seedjeffwan-spark-notebook
  namespace: yahavb
  - apiVersion: kubeflow.org/v1beta1
    controller: true
    kind: Notebook
    name: seedjeffwan-spark-notebook
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      statefulset: seedjeffwan-spark-notebook
  serviceName: ""
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seedjeffwan-spark-notebook
        notebook-name: seedjeffwan-spark-notebook
        statefulset: seedjeffwan-spark-notebook
    spec:
      containers:
      - env:
        - name: NB_PREFIX
          value: /notebook/yahavb/seedjeffwan-spark-notebook
        image: seedjeffwan/spark-notebook:0.1.1
        imagePullPolicy: IfNotPresent
        name: seedjeffwan-spark-notebook
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/jovyan
          name: workspace-seedjeffwan-spark-notebook
        - mountPath: /dev/shm
          name: dshm
        workingDir: /home/jovyan
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 100
      serviceAccount: default-editor
      serviceAccountName: default-editor
      terminationGracePeriodSeconds: 30
      volumes:
      - name: workspace-seedjeffwan-spark-notebook
        persistentVolumeClaim:
          claimName: workspace-seedjeffwan-spark-notebook
      - emptyDir:
          medium: Memory
        name: dshm
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
