#!/bin/bash
cd .
pwd
branch_name="b_"$RANDOM
git checkout -b $branch_name
git add *
git commit -m $branch_name
git push --set-upstream origin $branch_name
git checkout master
git branch -d $branch_name
git pull
