apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-us-west-2
  region: us-west-2

nodeGroups:
  - name: p3od
    labels:  
      project: zip
    maxSize: 10
    minSize: 0
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    instancesDistribution:
      instanceTypes: ["p3.2xlarge","p3.8xlarge"]
    tags:
      k8s.io/cluster-autoscaler/node-template/label/project: zip
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
