apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simpletcp
    release: r1
  name: simpletcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpletcp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpletcp
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: m5spot
      containers:
      - name: simpletcp
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/tcp-server
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
