---                                                                                 
kind: ClusterRole                                                                   
apiVersion: rbac.authorization.k8s.io/v1                                            
metadata:
  name: stk
  namespace: default                                                                
rules:
- apiGroups:                                                                        
  - ""
  resources:                                                                        
  - "*"                                                                             
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io                                                       
  - extensions 
  - apps
  resources:
  - "*"
  verbs:
  - "*" 
- apiGroups:                                                                        
  - apiextensions.k8s.io                                                            
  resources:
  - customresourcedefinitions                                                       
  - pods
  - deployments
  verbs:
  - get 
  - list
  - watch 
  - create  
  - delete  
---   
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: stk
---       
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stk
  namespace: default
subjects:
- kind: ServiceAccount
  name: stk
  namespace: default
roleRef:
  kind: ClusterRole
  name: stk
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: stk
    release: r1
  name: stk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stk
  serviceName: "stk"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stk
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: m5spot
      serviceAccountName: stk
      containers:
      - name: stk-sidecar
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/stk-sidecar:0.1
        imagePullPolicy: Always
        command: ["./start.sh"]
        env:
        - name: WAIT_TO_PLAYERS
          value: "120"
        - name: FREQ_CHECK_SESSION
          value: "10"
        - name: NUM_IDLE_SESSION
          value: "5"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
      - name: stk
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/supertuxkart:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: UDP
        command: ["./start.sh"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
