apiVersion: v1
kind: Service
metadata:
  name: stk-0
spec:
  selector:
    statefulset.kubernetes.io/pod-name: stk-0
  type: NodePort
  ports:
    - protocol: UDP
      port: 8080
      targetPort: 8080
---
