apiVersion: v1
kind: Service
metadata:
  name: supertuxkart-svc
spec:
  selector:
    app: supertuxkart
  type: NodePort
  ports:
    - protocol: UDP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: supertuxkart
    release: r1
  name: supertuxkart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supertuxkart
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: supertuxkart
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: m5spot
      containers:
      - name: supertuxkart
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/supertuxkart:0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["./start.sh"]
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
