FROM public.ecr.aws/m2l1d0b2/arm64v8-python-2
RUN apt-get update -y
RUN apt-get install -y sqlite3 
RUN apt-get install -y vim net-tools telnet
RUN /usr/local/bin/python -m pip install --upgrade pip
ADD deps /deps
ADD src /src
ADD server-py2.py /server.py
ADD world.py /world.py
ADD builder.py /builder.py
RUN gcc -std=c99 -O3 -fPIC -shared -o world -I src -I deps/noise deps/noise/noise.c src/world.c

ADD start.sh /start.sh
ADD monitor_active_game_sessions.sh /monitor_active_game_sessions.sh
