apiVersion: v1
data:
  PGHOST: c21icjJ5NHVjOWJra2YuY3VmYmZic2Rid2FjLnVzLXdlc3QtMi5yZHMuYW1hem9uYXdzLmNvbQ==
  PGPASSWORD: QWRtaW4xMjM0
  PGUSER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
