apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessionservers.zalando.org
spec:
  scope: Namespaced
  group: zalando.org
  names:
    kind: SessionSserver
    plural: sessionservers
    singular: sessionserver
    shortNames:
      - sss
      - ss
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
