FROM $BASE_IMAGE
ARG S3_LYRA_ASSETS
ARG GAME_SERVER_TAG
ENV S3_LYRA_ASSETS=$S3_LYRA_ASSETS
ENV GAME_SERVER_TAG=$GAME_SERVER_TAG
RUN wget "https://"$S3_LYRA_ASSETS".s3.us-west-2.amazonaws.com/cli_udp_game_session_cap.txt" -O /cli_udp_game_session_cap.txt
COPY . .
#RUN tar -xvf enet-1.3.17.tar
#RUN /enet-1.3.17/configure && make && make install
RUN pip install pyenet
