apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: arm-us-west-2
  version: "1.21"
  region: us-west-2

kubernetesNetworkConfig:
  ipFamily: IPv4

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.10.1-eksbuild.1 # optional
  - name: coredns
    version: v1.8.4-eksbuild.1 # optional
  - name: kube-proxy
    version: v1.21.2-eksbuild.2 # optional


managedNodeGroups:
  - instanceType: "c6g.xlarge"
    amiFamily: AmazonLinux2
    name: arm-ng-1
    desiredCapacity: 1
    maxSize: 10
    minSize: 1
    tags:
      project: supertuxkart
    labels:
      project: supertuxkart
