apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: stksrv
spec:
  requirements:
  - key: karpenter.k8s.aws/instance-cpu
    operator: Lt 
    values:
    - "5"
  - key: kubernetes.io/arch
    operator: In
    values:
    - arm64
    - amd64
  - key: karpenter.k8s.aws/instance-category
    operator: In
    values:
    - a
    - c
    - d
    - m
    - r
    - t
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
    - on-demand
  limits:
    resources:
      cpu: 20k
  providerRef:
    name: stksrv
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: stksrv
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        iops: 10000
        deleteOnTermination: true
        throughput: 125
  securityGroupSelector:
    karpenter.sh/discovery: $CLUSTER_NAME
  subnetSelector:
    karpenter.sh/discovery: $CLUSTER_NAME
