FROM 441218111557.dkr.ecr.us-west-2.amazonaws.com/baseimage:multiarch-py3
ARG SVN_STK
ENV SVN_STK=https://svn.code.sf.net/p/supertuxkart/code/stk-assets
RUN svn co https://svn.code.sf.net/p/supertuxkart/code/stk-assets stk-assets
