apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: knative-serving-install
  app.kubernetes.io/instance: knative-serving-install-v0.11.1
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: knative-serving-install
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.11.1
kind: Kustomization
namespace: knative-serving
resources:
- overlays/application/application.yaml
