apiVersion: v1
kind: Service
metadata:
  name: agones-ping-udp-service
  namespace: agones-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: udp
    nodePort: 30517
    port: 50000
    protocol: UDP
    targetPort: 8080
  selector:
    agones.dev/role: ping
  sessionAffinity: None
  type: LoadBalancer
