apiVersion: agones.dev/v1
kind: GameServer
metadata:
  labels:
    app: stk
    release: r1
  name: stk
spec:
  health: 
    disabled: true
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 8080
    protocol: UDP
  serviceName: "stk"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stk
    spec:
      nodeSelector:
        project: agones
      containers:
      - name: stk
        image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/supertuxkart-example:0.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2048m
            memory: 2048Mi
