---                                                                                 
kind: ClusterRole                                                                   
apiVersion: rbac.authorization.k8s.io/v1                                            
metadata:
  name: stk
  namespace: default                                                                
rules:
- apiGroups:                                                                        
  - ""
  resources:                                                                        
  - "*"                                                                             
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io                                                       
  - extensions 
  - apps
  resources:
  - "*"
  verbs:
  - "*" 
- apiGroups:                                                                        
  - apiextensions.k8s.io                                                            
  resources:
  - customresourcedefinitions                                                       
  - pods
  - deployments
  verbs:
  - get 
  - list
  - watch 
  - create  
  - delete  
---   
apiVersion: v1 
kind: ServiceAccount
metadata:
  name: stk
---       
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stk
  namespace: default
subjects:
- kind: ServiceAccount
  name: stk
  namespace: default
roleRef:
  kind: ClusterRole
  name: stk
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: agones.dev/v1
kind: GameServer
metadata:
  labels:
    app: stk
    release: r1
  name: stk
spec:
  health: 
    disabled: true
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 8080
    protocol: UDP
  serviceName: "stk"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stk
    spec:
      nodeSelector:
        nodetype: fleetiq
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: stk
        image: 163538056407.dkr.ecr.us-west-2.amazonaws.com/stk:0.3
        imagePullPolicy: Always
        command: ["./start.sh"]
        env:
        - name: SHARED_FOLDER
          value: "/sharedata"
        - name: WAIT_TO_PLAYERS
          value: "120"
        - name: GAME_SERVER_GROUP_NAME 
          value: "agonsegs"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: shared-data
          mountPath: /sharedata
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
