# Generated by Django 4.1.4 on 2022-12-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='username',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
    ]
